# Generated by Django 5.0 on 2024-01-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0002_cartitem_variations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="variations",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
